apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailoring-app-ingress
  namespace: tailoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - boutique.beework.in
    secretName: tailoring-app-tls-secret
  rules:
  - host: boutique.beework.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tailoring-app-service
            port:
              number: 80
