apiVersion: v1
kind: Service
metadata:
  name: tailoring-app-service
spec:
  type: NodePort
  selector:
    app: tailoring-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
